<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

<script>
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('aaa')
    },1000)
  }).then((res) => {
    console.log(res,'第一层的10行处理代码')
    //这里没有进行异步操作。
    //这里的目的是拿到resolve,并调用resolve,对res进行一些额外操作
    return new Promise((resolve) => {
      resolve(res + '111')
    })
  }).then(res => {
    console.log(res,'第二层的10行处理代码')
    return new Promise((resolve) => {
      resolve(res + '222')
    })
  }).then(res => {
    console.log(res,'第三层的10行处理代码')
  })

  //简写1 new Promise(resolve => resolve(res))
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('aaa')
    },1000)
  }).then((res) => {
    console.log(res,'第一层的10行处理代码')
    //这里没有进行异步操作。
    //这里的目的是拿到resolve,并调用resolve,对res进行一些额外操作
    return Promise.resolve(res + '111')
  }).then(res => {
    console.log(res,'第二层的10行处理代码')
    return Promise.resolve(res + '222')
  }).then(res => {
    console.log(res,'第三层的10行处理代码')
  })

  //简写2 new Promise(resolve => resolve(res))
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('aaa')
    },1000)
  }).then((res) => {
    console.log(res,'第一层的10行处理代码')
    //这里没有进行异步操作。
    //这里的目的是拿到resolve,并调用resolve,对res进行一些额外操作
    return res + '111'
  }).then(res => {
    console.log(res,'第二层的10行处理代码')
    return res + '222'
  }).then(res => {
    console.log(res,'第三层的10行处理代码')
  })

  //如果中间一步调用的不是resolve，而是调用reject,那么就不会进入下一个then函数，而是进入catch
  //也可以通过throw代替reject函数，去抛出异常，进入catch代码块
</script>
</body>
</html>